import { select, input } from '@inquirer/prompts';
import chalk from 'chalk';
import { writeFile } from 'node:fs/promises';
import type { Config } from '../../models/config.model.js';
import { IssueStore } from '../../store/store.js';
import { MilestonePlanRunner, type MilestoneSuggestion, type MilestonePlanResults } from './runner.js';

type OutputDecision = 'save' | 'regenerate' | 'done';

const EFFORT_LABELS: Record<string, string> = {
  small: 'small (1-2 weeks)',
  medium: 'medium (2-4 weeks)',
  large: 'large (4+ weeks)',
};

const PRIORITY_COLORS: Record<string, (s: string) => string> = {
  critical: chalk.red,
  high: chalk.yellow,
  medium: chalk.blue,
  low: chalk.dim,
};

export class MilestonePlanInteractiveUI {
  private store: IssueStore;
  private config: Config;

  constructor(store: IssueStore, config: Config) {
    this.store = store;
    this.config = config;
  }

  async present(): Promise<void> {
    console.log('');
    console.log(chalk.bold('Milestone Planner'));
    console.log('─'.repeat(55));

    const runner = new MilestonePlanRunner(this.store, this.config);
    let results = await runner.plan();

    if (results.isEmpty) {
      console.log(results.message ?? 'No milestone plan generated.');
      return;
    }

    let done = false;
    while (!done) {
      this.renderPlan(results);

      const decision = await select<OutputDecision>({
        message: 'What next?',
        choices: [
          { name: 'Save plan to file', value: 'save' },
          { name: 'Regenerate with different grouping', value: 'regenerate' },
          { name: 'Done', value: 'done' },
        ],
      });

      if (decision === 'save') {
        await this.saveToFile(results);
      } else if (decision === 'regenerate') {
        results = await runner.plan();
        if (results.isEmpty) {
          console.log(results.message ?? 'No milestone plan generated.');
          return;
        }
      } else {
        done = true;
      }
    }
  }

  private renderPlan(results: MilestonePlanResults): void {
    console.log('');
    console.log('═'.repeat(55));

    for (const [i, ms] of results.milestones.entries()) {
      console.log('');
      console.log(chalk.bold(`MILESTONE ${i + 1}: ${ms.name}`));
      console.log(`  Theme: ${ms.theme}`);
      console.log(`  Effort: ${EFFORT_LABELS[ms.effort] ?? ms.effort}`);
      console.log(`  ${'─'.repeat(45)}`);

      for (const issue of ms.issues) {
        const priority = issue.priority ?? 'unscored';
        const color = PRIORITY_COLORS[priority] ?? chalk.dim;
        console.log(`  #${String(issue.number).padEnd(5)} ${color(priority.padEnd(9))} ${issue.title}`);
      }
    }

    if (results.unassigned.length > 0) {
      console.log('');
      console.log(chalk.dim(`UNASSIGNED (${results.unassigned.length} issues)`));
      for (const issue of results.unassigned) {
        console.log(chalk.dim(`  #${String(issue.number).padEnd(5)} ${issue.title}`));
      }
    }

    console.log('');
    console.log('═'.repeat(55));
  }

  private async saveToFile(results: MilestonePlanResults): Promise<void> {
    const filePath = await input({
      message: 'Save to file:',
      default: 'MILESTONES.md',
    });

    try {
      const markdown = this.buildMarkdown(results);
      await writeFile(filePath, markdown, 'utf-8');
      console.log(chalk.green(`  ✓ Saved to ${filePath}`));
    } catch (error) {
      console.error(chalk.red(`  Failed to save: ${(error as Error).message}`));
    }
  }

  private buildMarkdown(results: MilestonePlanResults): string {
    const lines: string[] = [];
    const date = new Date().toISOString().split('T')[0];
    lines.push(`# Milestone Plan — ${date}`);
    lines.push('');

    for (const [i, ms] of results.milestones.entries()) {
      lines.push(`## Milestone ${i + 1}: ${ms.name}`);
      lines.push('');
      lines.push(`**Theme:** ${ms.theme}`);
      lines.push(`**Effort:** ${EFFORT_LABELS[ms.effort] ?? ms.effort}`);
      lines.push(`**Rationale:** ${ms.rationale}`);
      lines.push('');
      lines.push('| Issue | Priority | Title |');
      lines.push('|-------|----------|-------|');
      for (const issue of ms.issues) {
        lines.push(`| #${issue.number} | ${issue.priority ?? 'unscored'} | ${issue.title} |`);
      }
      lines.push('');
    }

    if (results.unassigned.length > 0) {
      lines.push('## Unassigned');
      lines.push('');
      lines.push('Issues that don\'t fit any milestone theme:');
      lines.push('');
      for (const issue of results.unassigned) {
        lines.push(`- #${issue.number} — ${issue.title}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('*Generated by Cezar*');
    lines.push('');

    return lines.join('\n');
  }
}
